name: Publish
on:
  push:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: test

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: devbox installer
        # You may pin to the exact commit or the version.
        # uses: jetify-com/devbox-install-action@a03caf5813591bc882139eba6ae947930a83a427
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          # Caching the entire Nix store in github based on your devbox.json
          enable-cache: true # optional, default is false
          # Specify devbox CLI version you want to pin to. Default to latest
          devbox-version: 0.13.5 # optional, default is

      - name: Publish package
        run: devbox run publish
