name: Test

on:
  push:
  workflow_call:

permissions:
  contents: read

jobs:
  verify-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: devbox installer
        # You may pin to the exact commit or the version.
        # uses: jetify-com/devbox-install-action@a03caf5813591bc882139eba6ae947930a83a427
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          # Caching the entire Nix store in github based on your devbox.json
          enable-cache: true # optional, default is false
          # Specify devbox CLI version you want to pin to. Default to latest
          devbox-version: 0.13.5 # optional, default is

      - name: Verify formatting
        run: devbox run deno fmt --check

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: devbox installer
        # You may pin to the exact commit or the version.
        # uses: jetify-com/devbox-install-action@a03caf5813591bc882139eba6ae947930a83a427
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          # Caching the entire Nix store in github based on your devbox.json
          enable-cache: true # optional, default is false
          # Specify devbox CLI version you want to pin to. Default to latest
          devbox-version: 0.13.5 # optional, default is

      - name: Run linter
        run: devbox run deno lint

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: devbox installer
        # You may pin to the exact commit or the version.
        # uses: jetify-com/devbox-install-action@a03caf5813591bc882139eba6ae947930a83a427
        uses: jetify-com/devbox-install-action@v0.11.0
        with:
          # Caching the entire Nix store in github based on your devbox.json
          enable-cache: true # optional, default is false
          # Specify devbox CLI version you want to pin to. Default to latest
          devbox-version: 0.13.5 # optional, default is

      - name: Run tests
        run: devbox run deno test
